name: Build
on:
  push:
    tags: ["v*"]
jobs:
  build_wheel:
    name: Build wheel
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install requirements
        run: python -m pip install -r requirements.txt
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Build
        run: |
          PYPROJECT_VERSION=$(echo ${{ github.ref }} | tr -d 'v'
          sed -i s'/version = ".*"/version = "'${PYPROJECT_VERSION}'"/' pyproject.toml
          python -m build
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/*.whl
          asset_content_type: application/zip

      