name: Test
on: [pull_request]
jobs:
  build_wheel:
    name: Build wheel
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install requirements
        run: python -m pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest
       - name: Set pyproject version
        run: |
          PYPROJECT_VERSION=0.0.1
          sed -i s'/version = ".*"/version = "'${PYPROJECT_VERSION}'"/' pyproject.toml
          python -m build
      - name: List artifacts
        run: ls -1 dist
